app/src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_participants;

    /**
     * @ORM\Column(type="boolean")
     */
    private $approval_status;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $creator;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $deleted_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNumberParticipants(): ?int
    {
        return $this->number_participants;
    }

    public function setNumberParticipants(int $number_participants): self
    {
        $this->number_participants = $number_participants;

        return $this;
    }

    public function isApprovalStatus(): ?bool
    {
        return $this->approval_status;
    }

    public function setApprovalStatus(bool $approval_status): self
    {
        $this->approval_status = $approval_status;

        return $this;
    }

    public function getCreator(): ?string
    {
        return $this->creator;
    }

    public function setCreator(?string $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(\DateTimeImmutable $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }
}

app/src/Form/CreateEventFormType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class CreateEventFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateTimeType::class)
            ->add('name', TextType::class)
            ->add('description', TextareaType::class)
            ->add('number_participants', IntegerType::class)
            ->add('approval_status', CheckboxType::class)
            ->add('submit', SubmitType::class, [
                'attr' => ['class' => 'btn btn-primary w-100']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

app/src/Controller/ConfirmationEventController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Utilities\GenerateConfirmationToken;

class ConfirmationEventController extends AbstractController
{
    /**
     * @Route("/confirmation/event", name="app_confirmation_event")
     */
    public function index(GenerateConfirmationToken $token): Response
    {
        //Generate a token for the event confirmation
        //Should I use a session to control the token?
        $my_token = $token->tokenize();
        return $this->render('confirmation_event/index.html.twig', [
            'my_token' => $my_token,
        ]);
    }
}

app/src/Controller/CreateEventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\CreateEventFormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CreateEventController extends AbstractController
{
    /**
     * @Route("/create/event", name="app_create_event")
     */
    public function index(Request $request): Response
    {
        //Handle form and event to POST request
        $event = new Event();
        $form = $this->createForm(CreateEventFormType::class, $event);
        $form->handleRequest($request);
        //Submit form and validate it
        if($form->isSubmitted() && $form->isValid()) {
            $event = $form->getData();
            $event->setCreatedAt(new \DateTimeImmutable());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_confirmation_event');
        }
        return $this->render('create_event/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

app/src/Controller/ViewEventController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Event;
use App\Repository\EventRepository;

class ViewEventController extends AbstractController
{
    /**
     * @Route("/view/event", name="app_view_event")
     */
    public function index(EventRepository $repo):Response
    {
        //Show only approved events
        $events = $repo->findBy(['approval_status' => true]);
        return $this->render('view_event/index.html.twig', [
            'events' => $events,
        ]);
    }
}

app/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        {# META TAG RESPONSIVE#}
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# BOOTSTRAP CDN #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {{ include('common/navbar.html.twig') }}
        {% block body %}{% endblock %}
        {{ include('common/footer.html.twig') }}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/templates/common/footer.html.twig
<div class="Footer">
    <p class="h3 text-center">© 2022 Carlos Eduardo.  All rights reserved.</p>
</div>

app/templates/common/navbar.html.twig
<div class="container-fluid container">
  <nav class="navbar navbar-expand-lg navbar-light">
    <span class="navbar-brand fw-bolder">Shining Events</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarText">
      <ul class="navbar-nav align-items-center">
        <li class="nav-item active">
          <a class="nav-link" href="{{ path('app_view_event')}}">Show events</a>
        </li>
        <li class="nav-item">
          <a href="{{ path('app_create_event') }}" class="btn btn-success">
          Create event
          </a>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/templates/confirmation_event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Confirm event!{% endblock %}

{% block body %}
<style>
    .ListToken-item {
        list-style:square;
        font-size:2em;
    }
</style>

<div class="container text-center">
    <div class="row">
        <div class="col-md-12">
            <h1>Hello user! OKAY ✅</h1>
            This friendly confirmation message:
            <ul class="ListToken">
                <li class="ListToken-item">Your confirmation token:<code> {{ my_token }}</code></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

app/templates/create_event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Create an Event {% endblock %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% block body %}
<style>
    .maxHeight{
        max-height:100vh;
    }
    .fullHeight{
        height:82vh;
    }
</style>

<div class="container Wrapper maxHeight fullHeight">
    <div class="row align-items-center h-100">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Create Event</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-md-offset-0">
                            <form action="{{ path('app_create_event') }} " method="POST" enctype="multipart/form-data">
                                {{ form_row(form.name) }}
                                {{ form_row(form.description) }}
                                {{ form_row(form.date) }}
                                {{ form_row(form.number_participants) }}
                                {{ form_row(form.approval_status) }}
                                {{ form_row(form.submit) }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/view_event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ViewEventController!
{% endblock %}

{% block body %}
	<style>
        .card-img-top {
            height:40vh;
        }
    </style>

	<div class="container">
		<h1 class="text-center">Approved Events</h1>
		<p class="text-center text-danger">Events that have not been approved will not be shown!
		</p>
        {% if events %}
            {% for event in events %}
                <h1 class="text-center">{{ event.creator }} </h1>
                <div class="card text-center mb-2">
                    <img class="card-img-top" src="{{ asset('/images/' ~ 'event_image.jpeg' ) }}" alt="Card image cap">
                    <div class="card-header">
                    Event ID:  {{event.id}}
                    </div>
                    <div class="card-body">
                        Name: <h5 class="card-title">{{event.name}}</h5>
                        Description: <p class="card-text">{{event.description}}</p>
                        <p class="card-text">Number of participants: {{event.numberParticipants}}</p>
                        {% if event.approvalStatus == true %}
                            <p class="card-text">Status: <span class="text-success"> Approved </span></p>
                        {% else %}
                            <p class="card-text">Status: <span class="text-danger"> Not Approved </span></p>
                        {% endif %}
                        <!-- <p class="card-text">Status: {{event.approvalStatus|replace({'1': "Approved", '0': "Not approved!"})}}</p> -->
                        <p class="card-text"> Authenticate: <span class="text-danger">Not authenticate </span></p>
                        <a href="#" class="btn btn-primary">Authenticate</a>
                    </div>
                    <div class="card-footer text-muted">
                        Event date: {{event.date|date}}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h1 class="text-center mb-3">No events found</h1>
        {% endif %}
	</div>
{% endblock %}